# Generated by Django 2.0.5 on 2018-06-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_drivejob_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivejob',
            name='recipient_email',
            field=models.EmailField(default='ishan@ishan1608.space', max_length=254),
            preserve_default=False,
        ),
    ]
