# Generated by Django 2.0.5 on 2018-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_drivejob_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivejob',
            name='file_name_suffix',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
